name: builder
on: [push]
jobs:
  builder-caddy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build eazy-caddy image
        run: |
          docker build . --tag ghcr.io/eazylaykzy/eazy-caddy:latest
#          docker run ghcr.io/eazylaykzy/eazy-caddy:latest
          docker push ghcr.io/eazylaykzy/eazy-caddy:latest
