name: builder

on: [push]

jobs:
  builder-caddy:
    permissions:
      actions: read
      checks: write
      contents: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Release build and push eazy-caddy image
        id: release_build
        uses: docker/build-push-action@v3
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64
          build-args: |
            Version=${{  env.TAG }}
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/eazy-caddy:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/eazy-caddy:latest


# permissions are needed if pushing to ghcr.io
#permissions:
#  packages: write
#
#jobs:
#  builder-caddy:
#    runs-on: ubuntu-latest
#    steps:
#      # Get the repository's code
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      # https://github.com/docker/setup-qemu-action
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      # https://github.com/docker/setup-buildx-action
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to GHCR
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Docker meta
#        id: quorum # you'll use this in the next step
#        uses: docker/metadata-action@v3
#        with:
#          # list of Docker images to use as base name for tags
#          images: |
#            ghcr.io/eazylaykzy/eazy-caddy
#          # Docker tags based on the following events/attributes
#          tags: |
#            type=schedule
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}
#            type=semver,pattern={{major}}
#            type=sha
#
#      - name: Build and push eazy-caddy image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          platforms: linux/arm64,linux/amd64
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.quorum.outputs.tags }}
#          labels: ${{ steps.quorum.outputs.labels }}

#jobs:
#  builder-caddy:
#    runs-on: ubuntu-latest
#    permissions:
#      packages: write
#    steps:
#      - uses: actions/checkout@v2
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build eazy-caddy image
#        run: |
#          docker build . --tag ghcr.io/eazylaykzy/eazy-caddy:latest
#          docker push ghcr.io/eazylaykzy/eazy-caddy:latest
